### ISSUE TITLE
.tracked_files uses absolute paths

### ISSUE THREAD

**Issue by benwaffle** [apicollective/apibuilder-cli#38]
e.g:
```
---
flow:
  api:
    ruby_client:
    - "/web/flowmisc/billing/lib/flow_commerce/flow_api_v0_client.rb"
  api-internal:
    ruby_client:
    - "/web/flowmisc/billing/lib/flow_commerce/flow_api_internal_v0_client.rb"
```

So if a different user has a different project location, this might not delete all files, or might delete extra files that are needed.
