### ISSUE TITLE
CLI doesn't download different versions of generated code for the same API

### ISSUE THREAD

**Issue by fabiocognigni** [apicollective/apibuilder-cli#66]
When running `apibuilder update` with a `config` like below (note the same api declared with different versions) only the files for the version declared latest are downloaded:

```
my-api:
  version: 1.0.3
  generators:
    - ...
my-api:
  version: 2.0.0
  generators:
    - ...
```
